[2024-10-21T20:56:44.134+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-21T20:56:44.148+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bash_example.test_task scheduled__2024-10-20T00:13:00+00:00 [queued]>
[2024-10-21T20:56:44.155+0700] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bash_example.test_task scheduled__2024-10-20T00:13:00+00:00 [queued]>
[2024-10-21T20:56:44.156+0700] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-21T20:56:44.172+0700] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): test_task> on 2024-10-20 00:13:00+00:00
[2024-10-21T20:56:44.180+0700] {standard_task_runner.py:72} INFO - Started process 6213 to run task
[2024-10-21T20:56:44.192+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'bash_example', 'test_task', 'scheduled__2024-10-20T00:13:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/example_dag.py', '--cfg-path', '/var/folders/3z/w6kw66r93jxd4b5xvgpxfbkm0000gn/T/tmp2g4n_85b']
[2024-10-21T20:56:44.195+0700] {standard_task_runner.py:105} INFO - Job 28: Subtask test_task
[2024-10-21T20:56:44.267+0700] {task_command.py:467} INFO - Running <TaskInstance: bash_example.test_task scheduled__2024-10-20T00:13:00+00:00 [running]> on host macbook-pro-khxng-krissanapong.local
[2024-10-21T20:56:44.347+0700] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='bash_example' AIRFLOW_CTX_TASK_ID='test_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-20T00:13:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-20T00:13:00+00:00'
[2024-10-21T20:56:44.350+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-21T20:56:44.351+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-21T20:56:44.351+0700] {logging_mixin.py:190} INFO - Current task name:test_task state:running start_date:2024-10-21 13:56:44.148609+00:00
[2024-10-21T20:56:44.352+0700] {logging_mixin.py:190} INFO - Dag name:bash_example and current dag run status:running
[2024-10-21T20:56:44.352+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-21T20:56:44.354+0700] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/3z/w6kw66r93jxd4b5xvgpxfbkm0000gn/T
[2024-10-21T20:56:44.355+0700] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo "2024-10-20: Test task completed" >> $(pwd)/output/test.txt']
[2024-10-21T20:56:44.372+0700] {subprocess.py:86} INFO - Output:
[2024-10-21T20:56:44.425+0700] {subprocess.py:93} INFO - /bin/bash: /private/var/folders/3z/w6kw66r93jxd4b5xvgpxfbkm0000gn/T/airflowtmppabd2bd2/output/test.txt: No such file or directory
[2024-10-21T20:56:44.426+0700] {subprocess.py:97} INFO - Command exited with return code 1
[2024-10-21T20:56:44.448+0700] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-21T20:56:44.456+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-21T20:56:44.457+0700] {logging_mixin.py:190} INFO - Task start:2024-10-21 13:56:44.148609+00:00 end:2024-10-21 13:56:44.455826+00:00 duration:0.307217
[2024-10-21T20:56:44.458+0700] {logging_mixin.py:190} INFO - Task:<Task(BashOperator): test_task> dag:<DAG: bash_example> dagrun:<DagRun bash_example @ 2024-10-20 00:13:00+00:00: scheduled__2024-10-20T00:13:00+00:00, state:running, queued_at: 2024-10-21 13:56:36.301191+00:00. externally triggered: False>
[2024-10-21T20:56:44.460+0700] {logging_mixin.py:190} INFO - Failure caused by Bash command failed. The command returned a non-zero exit code 1.
[2024-10-21T20:56:44.461+0700] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=bash_example, task_id=test_task, run_id=scheduled__2024-10-20T00:13:00+00:00, execution_date=20241020T001300, start_date=20241021T135644, end_date=20241021T135644
[2024-10-21T20:56:44.473+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-21T20:56:44.475+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task test_task (Bash command failed. The command returned a non-zero exit code 1.; 6213)
Traceback (most recent call last):
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/punny/Documents/GitHub/NYC-Taxi-ETL-Pipeline/.venv/lib/python3.10/site-packages/airflow/operators/bash.py", line 249, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-10-21T20:56:44.492+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-21T20:56:44.518+0700] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-21T20:56:44.523+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
